#!/usr/bin/env python3
"""Generate a buildah/podman-compatible Dockerfile from the heredoc-based
source Dockerfile.

Docker BuildKit natively understands `RUN <<name ... name` heredocs; buildah
(the OCI builder podman uses) does not -- Debian/Ubuntu's buildah package
deliberately reverted heredoc support to avoid vendoring an unpackaged
buildkit dependency. This script extracts each heredoc body into a real
`.sh` file under container/build/ and rewrites the RUN into a
--mount=type=bind + `bash -eo pipefail` invocation buildah can run, writing
the result to Dockerfile.podman.

Dockerfile stays the single source of truth (and is what Docker itself
builds, unmodified) -- Dockerfile.podman and container/build/*.sh are
generated on every run and gitignored.

Naming: the heredoc delimiter itself (e.g. `EOF`) stays generic and carries
no meaning. Instead, the FIRST line of every heredoc body must be a
`# name: <script>.sh` comment, which this script requires (erroring with the
line number if it's missing) and strips before writing the body out --
so the delimiter word doesn't need to be unique or descriptive, and the
generated script never carries the naming comment as dead code.

Two earlier designs were tried and rejected based on real `docker build`
testing (checking whether the heredoc body actually executed via a marker
file, not just build exit code):
  - A trailing `# name: ...` comment on *both* the opener and terminator
    lines breaks the build outright with "unterminated heredoc".
  - A trailing comment on the *opener* line only, with a bare terminator,
    builds successfully but the heredoc body silently never executes -- a
    trap, since it looks like success.
Putting the name on its own line, as real heredoc body content, sidesteps
both: BuildKit's heredoc parsing only ever looks at the opener and
terminator lines, so a plain comment line in the body is inert to it (and a
harmless no-op under Docker BuildKit itself, which runs the body verbatim
including this script's own generated files).
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCKERFILE = REPO_ROOT / "Dockerfile"
DOCKERFILE_PODMAN = REPO_ROOT / "Dockerfile.podman"
BUILD_DIR = REPO_ROOT / "container" / "build"

# A heredoc opener line: optionally preceded by other text (RUN, or nothing
# for a --mount continuation line), ending in `<<delimiter` with nothing
# after it.
HEREDOC_OPENER_RE = re.compile(r"^(?P<prefix>.*?)<<(?P<delimiter>\S+)\s*$")

# The required first line of every heredoc body.
NAME_COMMENT_RE = re.compile(r"^\s*#\s*name:\s*(?P<name>\S+)\s*$")

GENERATED_HEADER = (
    "# GENERATED by container/gen_podman_dockerfile.py from Dockerfile -- do not edit\n"
)


def generate() -> None:
    lines = DOCKERFILE.read_text().splitlines()
    n = len(lines)

    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    for stale in BUILD_DIR.glob("*.sh"):
        stale.unlink()

    out_lines = []
    seen_names = set()
    i = 0
    while i < n:
        line = lines[i]
        m = HEREDOC_OPENER_RE.match(line)
        prefix = m.group("prefix").strip() if m else None
        if not m or prefix not in ("", "RUN"):
            out_lines.append(line)
            i += 1
            continue

        delimiter = m.group("delimiter")
        opener_lineno = i + 1
        i += 1

        if i >= n:
            raise ValueError(f"Dockerfile:{opener_lineno}: unterminated heredoc {delimiter!r}")
        name_m = NAME_COMMENT_RE.match(lines[i])
        if not name_m:
            raise ValueError(
                f"Dockerfile:{i + 1}: expected '# name: <script>.sh' as the first line "
                f"of the heredoc opened at line {opener_lineno}, got {lines[i]!r}"
            )
        script = name_m.group("name")
        if script in seen_names:
            raise ValueError(f"Dockerfile:{i + 1}: script name {script!r} reused -- names must be unique")
        seen_names.add(script)
        i += 1

        body_lines = []
        while i >= n or lines[i] != delimiter:
            if i >= n:
                raise ValueError(f"Dockerfile:{opener_lineno}: unterminated heredoc {delimiter!r}")
            body_lines.append(lines[i])
            i += 1
        i += 1  # skip past the terminator line

        (BUILD_DIR / script).write_text(GENERATED_HEADER + "\n".join(body_lines) + "\n")

        mount = f"--mount=type=bind,src=container/build/{script},dst=/tmp/{script}"
        if prefix == "RUN":
            out_lines.append(f"RUN {mount} \\")
        else:
            out_lines.append(f"  {mount} \\")
        out_lines.append(f"  bash -eo pipefail /tmp/{script}")

    DOCKERFILE_PODMAN.write_text(GENERATED_HEADER + "\n".join(out_lines) + "\n")


if __name__ == "__main__":
    generate()
    print(f"wrote {DOCKERFILE_PODMAN} and {len(list(BUILD_DIR.glob('*.sh')))} script(s) in {BUILD_DIR}", file=sys.stderr)
