#!/usr/bin/env python3
"""Generate a buildah/podman-compatible Dockerfile from the heredoc-based
source Dockerfile.

Docker BuildKit natively understands `RUN <<name ... name` heredocs; buildah
(the OCI builder podman uses) does not -- Debian/Ubuntu's buildah package
deliberately reverted heredoc support to avoid vendoring an unpackaged
buildkit dependency. This script extracts each heredoc body into a real
`.sh` file under container/build/ and rewrites the RUN into a
--mount=type=bind + `bash -eo pipefail` invocation buildah can run, writing
the result to Dockerfile.podman.

Dockerfile stays the single source of truth (and is what Docker itself
builds, unmodified) -- Dockerfile.podman and container/build/*.sh are
generated on every run and gitignored.

Naming: each heredoc's delimiter word IS the generated script's name, e.g.
`RUN <<apt-system-deps ... apt-system-deps` -> container/build/apt-system-deps.sh.
This was chosen after empirically confirming (real `docker build`, checking
whether the body actually executed via a marker file) that BuildKit is not
just strict but actively unsafe about anything else sharing the heredoc
opener/terminator lines: a trailing `# comment` on the terminator line breaks
the build outright, but a trailing comment on the *opener* line alone builds
successfully while silently never running the heredoc body at all. Reusing
the delimiter itself as the name adds no extra syntax and is the one variant
confirmed to actually execute.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCKERFILE = REPO_ROOT / "Dockerfile"
DOCKERFILE_PODMAN = REPO_ROOT / "Dockerfile.podman"
BUILD_DIR = REPO_ROOT / "container" / "build"

# A heredoc opener line: optionally preceded by other text (RUN, or nothing
# for a --mount continuation line), ending in `<<name` with nothing after it.
HEREDOC_OPENER_RE = re.compile(r"^(?P<prefix>.*?)<<(?P<name>\S+)\s*$")

GENERATED_HEADER = (
    "# GENERATED by container/gen_podman_dockerfile.py from Dockerfile -- do not edit\n"
)


def generate() -> None:
    lines = DOCKERFILE.read_text().splitlines()
    n = len(lines)

    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    for stale in BUILD_DIR.glob("*.sh"):
        stale.unlink()

    out_lines = []
    seen_names = set()
    i = 0
    while i < n:
        line = lines[i]
        m = HEREDOC_OPENER_RE.match(line)
        prefix = m.group("prefix").strip() if m else None
        if not m or prefix not in ("", "RUN"):
            out_lines.append(line)
            i += 1
            continue

        name = m.group("name")
        if name in seen_names:
            raise ValueError(f"Dockerfile:{i + 1}: heredoc name {name!r} reused -- names must be unique")
        seen_names.add(name)

        opener_lineno = i + 1
        body_lines = []
        i += 1
        while i >= n or lines[i] != name:
            if i >= n:
                raise ValueError(f"Dockerfile:{opener_lineno}: unterminated heredoc {name!r}")
            body_lines.append(lines[i])
            i += 1
        i += 1  # skip past the terminator line

        script = f"{name}.sh"
        (BUILD_DIR / script).write_text(GENERATED_HEADER + "\n".join(body_lines) + "\n")

        mount = f"--mount=type=bind,src=container/build/{script},dst=/tmp/{script}"
        if prefix == "RUN":
            out_lines.append(f"RUN {mount} \\")
        else:
            out_lines.append(f"  {mount} \\")
        out_lines.append(f"  bash -eo pipefail /tmp/{script}")

    DOCKERFILE_PODMAN.write_text(GENERATED_HEADER + "\n".join(out_lines) + "\n")


if __name__ == "__main__":
    generate()
    print(f"wrote {DOCKERFILE_PODMAN} and {len(list(BUILD_DIR.glob('*.sh')))} script(s) in {BUILD_DIR}", file=sys.stderr)
